# Generated by Django 6.0.4 on 2026-04-17 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', models.CharField(choices=[('gas', 'Gas'), ('electricity', 'Electricity'), ('water', 'Water'), ('internet', 'Internet')], help_text='Type of utility bill (Gas, Electricity, Water, Internet).', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount of the bill.', max_digits=10)),
                ('billing_period', models.CharField(blank=True, help_text="Actual billing period (e.g., 'March–April').", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('month', models.ForeignKey(help_text='Month the bill arrived (not necessarily the usage month).', on_delete=django.db.models.deletion.CASCADE, to='expenses.month')),
                ('paid_by', models.ForeignKey(help_text='Person who paid the bill upfront.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UtilityShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_owed', models.DecimalField(decimal_places=2, help_text='Amount this person owes for the bill.', max_digits=10)),
                ('has_paid', models.BooleanField(default=False, help_text='Has this person paid Jade back?')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='expenses.utilitybill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
